name: Build Go Hello World

on:
  push:
    branches:
      - master  # 当推送到 master 分支时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Extract short SHA
        run: |
          short_sha="${GITHUB_SHA:0:8}"
          echo "short_sha=$short_sha" >> $GITHUB_ENV
          echo "Short SHA: $short_sha"
      - name: Build Hello World
        run: |
          go build -o hello-world src/hello-world.go
          chmod +x hello-world
      - name: Build Docker image
        run: |
          docker build -t zazayaya/hello-world-go:${{ env.short_sha }} .
          docker tag zazayaya/hello-world-go:${{ env.short_sha }} zazayaya/hello-world-go:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Docker image to Docker Hub
        run: |
          docker push zazayaya/hello-world-go:latest
          docker push zazayaya/hello-world-go:${{ env.short_sha }}
